### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by hsluoyz** [casbin/Casbin.NET#292]
https://github.com/casbin/Casbin.NET/actions/runs/3079717027/jobs/4976271164

![image](https://user-images.githubusercontent.com/3787410/190945904-939984f1-8f82-464c-9d3f-548b2598934d.png)

**Comment by hsluoyz** [comment]
@AsakusaRinne after merging your PR: https://github.com/casbin/Casbin.NET/pull/284, caused this issue. Can you fix it?

/cc @sagilio

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne after merging your PR: #284, caused this issue. Can you fix it?
> 
> /cc @sagilio

It's not an error caused by the added unit test code of #284. It's in fact because of the new feature of C# 11 ([see this doc](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%207#instance-method-on-ref-struct-may-capture-unscoped-ref-parameters)), and the latest .NET 7.0 RC takes it.

The PR #289 which was merged into preview branch solved this ci error btw, by adding ```scoped``` to parameters with ```in```. I think the ci error would be solved after merging preview into master. @sagilio Plz help to have a look.

**Comment by hsluoyz** [comment]
@sagilio we should release new version soon

**Comment by hsluoyz** [comment]
Fixed
